"""盲盒奖池配置（03 §5）

标准盲盒：能量为主要产出，稀有度以上走保底。cost_energy=10 与 03 §5.1 一致。
"""
from __future__ import annotations

from core.gacha.gacha import GachaItem, GachaPool, GachaRarity

STANDARD_POOL = GachaPool(
    id="standard",
    name="标准盲盒",
    cost_energy=10.0,
    cost_tickets=1,
    guarantee_rare=10,
    items=[
        GachaItem(id="energy_s", name="小能量包", rarity=GachaRarity.COMMON,
                  item_type="energy", amount=10.0, weight=30.0, icon="🔋"),
        GachaItem(id="energy_l", name="大能量包", rarity=GachaRarity.COMMON,
                  item_type="energy", amount=20.0, weight=15.0, icon="⚡"),
        GachaItem(id="snack", name="随机零食", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="snack", weight=30.0, icon="🍪"),
        GachaItem(id="badge_star", name="星星徽章", rarity=GachaRarity.UNCOMMON,
                  item_type="badge", item_id="star_badge", weight=20.0, icon="⭐"),
        GachaItem(id="costume_scarf", name="围巾外观", rarity=GachaRarity.UNCOMMON,
                  item_type="costume", item_id="scarf", weight=15.0, icon="🧣"),
        GachaItem(id="gem", name="宝石", rarity=GachaRarity.RARE,
                  item_type="item", item_id="gem", weight=10.0, icon="💎"),
        GachaItem(id="g_apple", name="苹果", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="apple", weight=10.0, icon="🍎"),
        GachaItem(id="g_water", name="水", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="water", weight=8.0, icon="💧"),
        GachaItem(id="g_coffee", name="咖啡", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="coffee", weight=8.0, icon="☕"),
        GachaItem(id="g_fish", name="小鱼干", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="fish", weight=6.0, icon="🐟"),
        GachaItem(id="g_toy", name="毛线球", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="toy_ball", weight=8.0, icon="🧶"),
        GachaItem(id="g_treat", name="小零食", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="treat", weight=10.0, icon="🍪"),
        # ── 食物类（虚拟收集物，未来可映射用户画作）──
        GachaItem(id="g_strawberry", name="草莓", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="strawberry", weight=8.0, icon="🍓"),
        GachaItem(id="g_banana", name="香蕉", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="banana", weight=8.0, icon="🍌"),
        GachaItem(id="g_cake", name="蛋糕", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="cake", weight=5.0, icon="🍰"),
        GachaItem(id="g_riceball", name="饭团", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="rice_ball", weight=6.0, icon="🍙"),
        GachaItem(id="g_carrot", name="胡萝卜", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="carrot", weight=8.0, icon="🥕"),
        GachaItem(id="g_bread", name="面包", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="bread", weight=7.0, icon="🍞"),
        GachaItem(id="g_cheese", name="奶酪", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="cheese", weight=6.0, icon="🧀"),
        GachaItem(id="g_sushi", name="寿司", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="sushi", weight=5.0, icon="🍣"),
        GachaItem(id="g_honey", name="蜂蜜", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="honey", weight=5.0, icon="🍯"),
        GachaItem(id="g_melon", name="蜜瓜", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="melon", weight=5.0, icon="🍈"),
        GachaItem(id="g_egg", name="鸡蛋", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="egg", weight=8.0, icon="🥚"),
        GachaItem(id="g_milk", name="牛奶", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="milk", weight=8.0, icon="🥛"),
        GachaItem(id="g_grape", name="葡萄", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="grape", weight=7.0, icon="🍇"),
        GachaItem(id="g_peach", name="桃子", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="peach", weight=6.0, icon="🍑"),
        GachaItem(id="g_watermelon", name="西瓜", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="watermelon", weight=4.0, icon="🍉"),
        # ── 玩具类 ──
        GachaItem(id="g_ball", name="弹力球", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="ball", weight=8.0, icon="🎾"),
        GachaItem(id="g_yoyo", name="悠悠球", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="yoyo", weight=6.0, icon="🪀"),
        GachaItem(id="g_teddy", name="泰迪熊", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="teddy", weight=4.0, icon="🧸"),
        GachaItem(id="g_balloon", name="气球", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="balloon", weight=6.0, icon="🎈"),
        GachaItem(id="g_kite", name="风筝", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="kite", weight=5.0, icon="🪁"),
        GachaItem(id="g_dice", name="骰子", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="dice", weight=6.0, icon="🎲"),
        GachaItem(id="g_cards", name="纸牌", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="cards", weight=6.0, icon="🃏"),
        GachaItem(id="g_dart", name="飞镖", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="dart", weight=5.0, icon="🎯"),
        GachaItem(id="g_puzzle", name="拼图", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="puzzle", weight=5.0, icon="🧩"),
        GachaItem(id="g_blocks", name="积木", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="blocks", weight=5.0, icon="🧱"),
        # ── 装饰 / 植物类 ──
        GachaItem(id="g_flower", name="小花", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="flower", weight=8.0, icon="🌸"),
        GachaItem(id="g_plant", name="盆栽", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="plant", weight=7.0, icon="🌿"),
        GachaItem(id="g_clover", name="四叶草", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="clover", weight=6.0, icon="🍀"),
        GachaItem(id="g_bell", name="铃铛", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="bell", weight=6.0, icon="🔔"),
        GachaItem(id="g_ribbon", name="蝴蝶结", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="ribbon", weight=6.0, icon="🎀"),
        GachaItem(id="g_candle", name="蜡烛", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="candle", weight=5.0, icon="🕯️"),
        GachaItem(id="g_shell", name="贝壳", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="shell", weight=6.0, icon="🐚"),
        GachaItem(id="g_mushroom", name="蘑菇", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="mushroom", weight=7.0, icon="🍄"),
        GachaItem(id="g_leaf", name="叶子", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="leaf", weight=7.0, icon="🍃"),
        GachaItem(id="g_heart", name="爱心", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="heart", weight=6.0, icon="💖"),
        GachaItem(id="g_bubble", name="泡泡", rarity=GachaRarity.COMMON,
                  item_type="item", item_id="bubble", weight=6.0, icon="🫧"),
        GachaItem(id="g_snowflake", name="雪花", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="snowflake", weight=4.0, icon="❄️"),
        GachaItem(id="g_sparkle", name="闪光", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="sparkle", weight=5.0, icon="✨"),
        GachaItem(id="g_rainbow", name="彩虹", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="rainbow", weight=3.0, icon="🌈"),
        GachaItem(id="g_feather", name="羽毛", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="feather", weight=5.0, icon="🪶"),
        GachaItem(id="g_musicnote", name="音符", rarity=GachaRarity.UNCOMMON,
                  item_type="item", item_id="music_note", weight=5.0, icon="🎵"),
        # ── 稀有收藏物 ──
        GachaItem(id="g_crystal", name="水晶球", rarity=GachaRarity.RARE,
                  item_type="item", item_id="crystal", weight=3.0, icon="🔮"),
        GachaItem(id="g_crown", name="小王冠", rarity=GachaRarity.RARE,
                  item_type="item", item_id="crown", weight=2.0, icon="👑"),
        GachaItem(id="g_gift", name="礼物盒", rarity=GachaRarity.RARE,
                  item_type="item", item_id="gift", weight=3.0, icon="🎁"),
        GachaItem(id="g_sapphire", name="蓝宝石", rarity=GachaRarity.RARE,
                  item_type="item", item_id="sapphire", weight=3.0, icon="💠"),
        GachaItem(id="guest_pet", name="客座桌宠", rarity=GachaRarity.EPIC,
                  item_type="character", item_id="guest_pet", weight=4.0, icon="🐾"),
        GachaItem(id="legend", name="传说形态", rarity=GachaRarity.LEGENDARY,
                  item_type="character", item_id="legend_pet", weight=1.0, icon="🌟"),
    ],
)


__all__ = ["STANDARD_POOL"]
